name: Black linter + isort

on: [push, pull_request]

jobs:
  apply_linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: isort/isort-action@master
        with:
          sort-paths: "./src"
      - uses: psf/black@stable
        with:
            options: "--check --verbose"
            src: "./src"
            version: "~= 22.0"