name: Tests

on: [push, pull_request]

jobs:
  run_tests_04:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip3 install --no-cache-dir -r requirements.txt
      - name: Run Tests
        run: python -m unittest discover -s test
